### ISSUE TITLE
reduce() producing wrong result?

### ISSUE THREAD

**Issue by domantasjurkus** [KhronosGroup/SyclParallelSTL#57]
Hello, I can't seem to figure out why the following code snippet produces 0 as a result:

```
    std::vector<int> v(8, 2);
    {
        sycl::sycl_execution_policy<> sycl_policy;
        auto t1 = std::chrono::high_resolution_clock::now();
        // Why is the result wrong?
        int result = std::experimental::parallel::reduce(sycl_policy, v.begin(), v.end(), 0);
        std::chrono::duration<double, std::milli> ms = std::chrono::high_resolution_clock::now() - t1;
        std::cout << "std::reduce result " << result << " took " << ms.count() << " ms\n";
    }
```

![reduction](https://user-images.githubusercontent.com/9018827/35097260-4a1dd9dc-fc47-11e7-85fa-75d453209a5c.png)

I make a repo where the issue can (hopefully) be reproduced. Note that the build dependencies are hard-coded in CMakeLists.txt:
https://github.com/domantasjurkus/parallel_stl_reduction

I am using Computecpp CE 0.5.1 and I did a fresh git put for SyclParallelSTL quite recently. The input size is 8 which is a power of 2. Not quite sure what else could be wrong.

**Comment by tremmelg** [comment]
I think it's because you are accidentally using a code path that's not tested with ComputeCpp. The `CMakeLists.txt` sets some additional flags when building the benchmarks and tests with ComputeCpp.
Could you try adding the two lines from the linked file to your `CMakeLists.txt`? See https://github.com/KhronosGroup/SyclParallelSTL/blob/master/CMakeLists.txt#L23

**Comment by domantasjurkus** [comment]
Worked like a charm, thanks!
