### ISSUE TITLE
Error when compiling test file count_if.cpp

### ISSUE THREAD

**Issue by JoanThibault** [KhronosGroup/SyclParallelSTL#6]
Hello,

When I tried to compile the tets file count_if.cpp, 'make' raises me an error at compile time which make me think that there is an implicit conversion from nd_item<1> to nd_item<3> in the file:
https://github.com/KhronosGroup/SyclParallelSTL/blob/master/include/sycl/algorithm/count_if.hpp#L88
which is likely to be a call to the constructor, located in this file :
https://github.com/KhronosGroup/SyclParallelSTL/blob/master/include/sycl/algorithm/algorithm_composite_patterns.hpp#L58

attached: 
The result from gcc when I try to compile count_if (attached below):
[make.log](https://github.com/KhronosGroup/SyclParallelSTL/files/579260/make.txt)
[count_if.cpp](https://github.com/KhronosGroup/SyclParallelSTL/files/579262/count_if.txt)
(this file is identical to https://github.com/KhronosGroup/SyclParallelSTL/blob/master/tests/count_if.cpp , except that I removed calls to GoogleTests)

Best regards

Joan Thibault

**Comment by keryell** [comment]
It looks like all the algorithms create a cl::sycl::nd_range<3> but count_if which creates a cl::sycl::nd_range<1>. They end to generate nd_item<3> and nd_item<1> respectively inside the kernels.
I guess it works with ComputeCpp because there is some extension, not found in triSYCL, providing a conversion from an nd_item<1> to an nd_item<3> with the 2 other coordinates set to 0.
It works probably because even if cl::sycl::nd_range<3> are used almost everywhere, it seems that the 2 last ranges are only 1, so basically a degenerated 3D iteration space representing 1D iteration space.
While it could be possible to update count_if to use 3D iteration space too, the whole SYCL ParallelSTL could be simplified to use only 1D iteration space...
Actually all the accessors seem to be 1D only too already.

**Comment by Ruyk** [comment]
You are correct! There is no need to use the 3D range, so I've replaced all to the 1D (See pull request #8) .  In ComputeCpp CE seems there is a conversion, which I don't think is explicitly banned by the SYCL specification? I've open an internal in ComputeCpp to look into this conversion issue.

**Comment by keryell** [comment]
Thank you for having moved to 1D everywhere. I guess it is more efficient that way.
Otherwise I have no issue with ComputeCpp providing implicit conversions.
It was just surprising for us that it was compiling with ComputeCpp and not triSYCL. ;-)

**Comment by JoanThibault** [comment]
Hi,
I downloaded files you modified from the 1d_range branch, it works fine =)
Thank you
